UPDATE Civilization_Religions SET ReligionType = 
	( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type="RELIGION_ONYAMESOM" )
		THEN "RELIGION_ONYAMESOM"
		ELSE "RELIGION_ISLAM" END
	) WHERE CivilizationType = "CIVILIZATION_RMOSSI"; 

CREATE TRIGGER ReligionRJMossiMod
AFTER INSERT ON Religions WHEN 'RELIGION_RELIGION_ONYAMESOM' = NEW.Type
BEGIN
	UPDATE Civilization_Religions 
	SET ReligionType = 'RELIGION_RELIGION_ONYAMESOM'
	WHERE CivilizationType IN ('CIVILIZATION_RMOSSI');
END;